package org.cloudburstmc.mojava.jmh;

import gg.moonflower.molangcompiler.api.MolangCompiler;
import gg.moonflower.molangcompiler.api.MolangEnvironment;
import gg.moonflower.molangcompiler.api.MolangExpression;
import gg.moonflower.molangcompiler.api.MolangRuntime;
import org.cloudburstmc.mojava.MoJava;
import org.cloudburstmc.mojava.compiler.MoScript;
import org.cloudburstmc.mojava.runtime.MoRuntime;
import org.cloudburstmc.mojava.runtime.value.DoubleValue;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;
import team.unnamed.mocha.MochaEngine;
import team.unnamed.mocha.runtime.MochaFunction;

import java.util.concurrent.TimeUnit;

/**
 * Compares this library against {@code gg.moonflower:molang-compiler:3.1.1.19} and
 * {@code team.unnamed:mocha:3.0.1} on the two operations every MoLang engine performs: turning a
 * source string into an executable form ({@code compile_*}) and evaluating that form ({@code eval_*}).
 *
 * <p>Run with {@code ./gradlew jmh}.
 *
 * <h2>The workloads</h2>
 * Three variable-driven scripts that all three dialects accept identically, named {@code mixed_*},
 * {@code trig_*}, {@code cond_*}:
 * <ul>
 *   <li><b>mixed</b> — the original combined script (trig + arithmetic + a ternary).</li>
 *   <li><b>trig</b> — a {@code math.sin}/{@code math.cos} animation curve.</li>
 *   <li><b>cond</b> — a single comparison-driven ternary.</li>
 * </ul>
 * Query-, string- and loop-based workloads are intentionally left out of the cross-engine set: the
 * three engines bind host queries differently, molang-compiler is float-only (no strings), and loop
 * support diverges — comparing them would measure different things. Those live in the mojava-only
 * {@link WorkloadBenchmark} (W1–W7) instead.
 *
 * <p>Each script reads one runtime variable {@code v.t} (seeded to 0), which keeps the comparison
 * honest across two dialect seams:
 * <ul>
 *   <li>molang-compiler <em>throws</em> on an unset variable, so {@code v.t} is seeded in its
 *       environment.</li>
 *   <li>mocha's bytecode compiler ({@code MochaEngine.compile}) emits invalid bytecode for any script
 *       that reads a {@code variable.}/{@code v.} reference, so mocha runs through its interpreter
 *       path, {@code prepareEval}. This is the one apples-to-oranges seam: mojava and molang-compiler
 *       run generated bytecode, mocha walks a prepared tree.</li>
 *   <li>Because {@code v.t} is a runtime variable (not a literal) no engine constant-folds the script
 *       away, so {@code *_eval_*} measures real evaluation work.</li>
 * </ul>
 *
 * <p>The {@code *_compile_*} numbers cover parse + executable-form construction (ASM bytecode for
 * mojava/molang-compiler, interpreter-tree prep for mocha); the {@code *_eval_*} numbers are the
 * steady-state hot path. mojava's eval uses {@code executeDouble} (the unboxed OPT-1/OPT-2 path).
 */
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
@Fork(2)
public class MolangBenchmark {

    private static final String MIXED =
            "math.cos(v.t * 38) * 2.0 + v.t * v.t + math.sqrt(v.t * v.t + 1.0) - (v.t > 1.0 ? v.t * 0.5 + 3.0 : v.t - 1.0) / 2.0";
    private static final String TRIG = "math.sin(v.t * 90) * 30 + math.cos(v.t * 45)";
    private static final String COND = "v.t > 1.0 ? v.t * 0.5 + 3.0 : v.t - 1.0";

    // mojava
    private MoRuntime mojavaRuntime;
    private MoScript mojavaMixed, mojavaTrig, mojavaCond;

    // mocha (interpreter path; see class javadoc)
    private MochaEngine<?> mochaEngine;
    private MochaFunction mochaMixed, mochaTrig, mochaCond;

    // molang-compiler
    private MolangCompiler mcCompiler;
    private MolangEnvironment mcEnv;
    private MolangExpression mcMixed, mcTrig, mcCond;

    @Setup
    public void setup() throws Exception {
        mojavaRuntime = MoJava.createRuntime();
        mojavaRuntime.getEnvironment().variable.setDirectly("t", DoubleValue.ZERO);
        mojavaMixed = mojavaRuntime.compile(MoJava.parse(MIXED));
        mojavaTrig = mojavaRuntime.compile(MoJava.parse(TRIG));
        mojavaCond = mojavaRuntime.compile(MoJava.parse(COND));

        mochaEngine = MochaEngine.createStandard();
        mochaMixed = mochaEngine.prepareEval(MIXED);
        mochaTrig = mochaEngine.prepareEval(TRIG);
        mochaCond = mochaEngine.prepareEval(COND);

        mcCompiler = MolangCompiler.create(MolangCompiler.DEFAULT_FLAGS, getClass().getClassLoader());
        mcEnv = MolangRuntime.runtime().setVariable("t", 0.0f).create();
        mcMixed = mcCompiler.compile(MIXED);
        mcTrig = mcCompiler.compile(TRIG);
        mcCond = mcCompiler.compile(COND);
    }

    // ---- compile: source string -> executable form ----

    @Benchmark public MoScript mixed_compile_mojava() { return mojavaRuntime.compile(MoJava.parse(MIXED)); }
    @Benchmark public MochaFunction mixed_compile_mocha() { return mochaEngine.prepareEval(MIXED); }
    @Benchmark public MolangExpression mixed_compile_molangCompiler() throws Exception { return mcCompiler.compile(MIXED); }

    @Benchmark public MoScript trig_compile_mojava() { return mojavaRuntime.compile(MoJava.parse(TRIG)); }
    @Benchmark public MochaFunction trig_compile_mocha() { return mochaEngine.prepareEval(TRIG); }
    @Benchmark public MolangExpression trig_compile_molangCompiler() throws Exception { return mcCompiler.compile(TRIG); }

    @Benchmark public MoScript cond_compile_mojava() { return mojavaRuntime.compile(MoJava.parse(COND)); }
    @Benchmark public MochaFunction cond_compile_mocha() { return mochaEngine.prepareEval(COND); }
    @Benchmark public MolangExpression cond_compile_molangCompiler() throws Exception { return mcCompiler.compile(COND); }

    // ---- eval: executable form -> double (mojava on the unboxed executeDouble path) ----

    @Benchmark public double mixed_eval_mojava() { return mojavaRuntime.executeDouble(mojavaMixed); }
    @Benchmark public double mixed_eval_mocha() { return mochaMixed.evaluate(); }
    @Benchmark public double mixed_eval_molangCompiler() throws Exception { return mcMixed.get(mcEnv); }

    @Benchmark public double trig_eval_mojava() { return mojavaRuntime.executeDouble(mojavaTrig); }
    @Benchmark public double trig_eval_mocha() { return mochaTrig.evaluate(); }
    @Benchmark public double trig_eval_molangCompiler() throws Exception { return mcTrig.get(mcEnv); }

    @Benchmark public double cond_eval_mojava() { return mojavaRuntime.executeDouble(mojavaCond); }
    @Benchmark public double cond_eval_mocha() { return mochaCond.evaluate(); }
    @Benchmark public double cond_eval_molangCompiler() throws Exception { return mcCond.get(mcEnv); }
}
