package org.cloudburstmc.mojava;

import org.cloudburstmc.mojava.compiler.BytecodeCompiler;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.util.CheckClassAdapter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.PrintWriter;
import java.io.StringWriter;

/** Exercises the generated bytecode and checks it passes the ASM verifier. */
@DisplayName("Compiler bytecode validity")
public class CompilerNodeTest {

    @ParameterizedTest
    @ValueSource(strings = {
            "1 + 2 * 3 - 4 / 2",
            "math.sin(90) + math.cos(0)",
            "v.a = 1; v.b = 2; return v.a + v.b;",
            "loop(5, { v.x = v.x + 1; (v.x > 3) ? break; });",
            "array.a.0 = 1; for_each(v.e, array.a, { v.s = v.s + v.e; }); return v.s;",
            "1 ? 2 : 3 ? 4 : 5",
            "v.x ?? 7",
            "1 && 0 || 1",
            "!0 + -3",
            "'a' == 'b'",
            "v.x = 1; return this->v.x;",
            "loop(3, { continue; v.x = 99; }); return v.x;",
    })
    @DisplayName("generated class verifies")
    public void verifies(String code) {
        byte[] bytes = BytecodeCompiler.compileToBytes(MoJava.parse(code));
        StringWriter sw = new StringWriter();
        CheckClassAdapter.verify(new ClassReader(bytes), false, new PrintWriter(sw));
        String report = sw.toString();
        Assertions.assertTrue(report.isEmpty(), () -> "Verifier errors for [" + code + "]:\n" + report);
    }
}
