package org.cloudburstmc.mojava.compiler;

import org.cloudburstmc.mojava.runtime.MoEnvironment;
import org.cloudburstmc.mojava.runtime.MoParams;
import org.cloudburstmc.mojava.runtime.struct.VariableStruct;
import org.cloudburstmc.mojava.runtime.value.DoubleValue;
import org.cloudburstmc.mojava.runtime.value.MoValue;
import org.cloudburstmc.mojava.runtime.value.StringValue;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Static helpers the generated bytecode calls into. Every piece of fiddly runtime logic (name-path
 * building, the string-vs-double rules of {@code +}, equality, {@code MoParams} construction) lives
 * here so the emitted bytecode stays small and the semantics match the interpreter exactly.
 */
public final class CompilerSupport {

    private CompilerSupport() {
    }

    // ---- name resolution ----
    // Name paths arrive as List<String> constants baked at compile time, so there is no per-call
    // Arrays.asList wrapper to allocate — only the iterator the struct API consumes.

    public static MoValue getValue(MoEnvironment env, List<String> names) {
        return env.getValue(names.iterator());
    }

    // Primitive-double name read for the numeric path: a registered double-query allocates nothing.
    public static double getValueDouble(MoEnvironment env, List<String> names) {
        return env.getValueDouble(names.iterator());
    }

    public static MoValue getRaw(MoEnvironment env, List<String> names) {
        return env.getRaw(names.iterator());
    }

    public static void setValue(MoEnvironment env, List<String> names, MoValue value) {
        env.setValue(names.iterator(), value);
    }

    // Fast path for two-segment variable/temp access (e.g. v.x, t.y): an array load at the compile-time
    // slot, skipping the name split, the getStruct switch, the iterator allocation, and the map hash.
    public static MoValue varGet(VariableStruct struct, int slot) {
        MoValue value = struct.slotGet(slot);
        return value != null ? value : DoubleValue.ZERO;
    }

    // Primitive-double variant for the Tier-2 numeric path: skips boxing to DoubleValue and the
    // asDouble interface dispatch. Matches varGet(...).asDouble() exactly (absent -> 0.0).
    public static double varGetDouble(VariableStruct struct, int slot) {
        MoValue value = struct.slotGet(slot);
        return value != null ? value.asDouble() : 0.0;
    }

    // The name rides along so the canonical map stays in sync for getMap()/for_each/dynamic reads.
    public static void varSet(VariableStruct struct, int slot, String name, MoValue value) {
        struct.slotSet(slot, name, value);
    }

    // FuncCallExpression with a statically-known name path.
    public static MoValue call(MoEnvironment env, List<String> names, MoValue[] args) {
        // args is the array the compiled call path already built; MoParams wraps it without copying.
        return env.getValue(names.iterator(), new MoParams(env, args));
    }

    // FuncCallExpression / ArrayAccessExpression where the name is computed at runtime.
    public static MoValue callDynamic(MoEnvironment env, String nameString, MoValue[] args) {
        return env.getValue(Arrays.asList(nameString.split("\\.")).iterator(), new MoParams(env, args));
    }

    // ArrayAccessExpression: append the clamped index to the base name path, then look up.
    public static MoValue arrayGet(MoEnvironment env, List<String> base, MoValue indexValue) {
        return env.getValue(arrayNames(base, indexValue).iterator());
    }

    public static void arraySet(MoEnvironment env, List<String> base, MoValue indexValue, MoValue value) {
        env.setValue(arrayNames(base, indexValue).iterator(), value);
    }

    public static MoValue arrayGetDynamic(MoEnvironment env, String baseString, MoValue indexValue) {
        return env.getValue(arrayNames(Arrays.asList(baseString.split("\\.")), indexValue).iterator());
    }

    public static void arraySetDynamic(MoEnvironment env, String baseString, MoValue indexValue, MoValue value) {
        env.setValue(arrayNames(Arrays.asList(baseString.split("\\.")), indexValue).iterator(), value);
    }

    private static List<String> arrayNames(List<String> base, MoValue indexValue) {
        List<String> names = new ArrayList<>(base);
        names.add(String.valueOf(Math.max(0, (int) indexValue.asDouble()))); // negative indices clamp to 0
        return names;
    }

    // ---- arithmetic / comparison (mirror the binaryop AST nodes) ----

    public static MoValue add(MoValue left, MoValue right) {
        // Molang strings support only == and !=; '+' is not concatenation. A string operand here is a
        // runtime content error (e.g. a variable that turned out to hold a string), resolved to 0.0.
        if (left instanceof StringValue || right instanceof StringValue) {
            return DoubleValue.ZERO;
        }
        return new DoubleValue(left.asDouble() + right.asDouble());
    }

    public static MoValue subtract(MoValue left, MoValue right) {
        return new DoubleValue(left.asDouble() - right.asDouble());
    }

    public static MoValue multiply(MoValue left, MoValue right) {
        return new DoubleValue(left.asDouble() * right.asDouble());
    }

    public static MoValue divide(MoValue left, MoValue right) {
        return new DoubleValue(left.asDouble() / right.asDouble());
    }

    public static MoValue equal(MoValue left, MoValue right) {
        return boolVal(left.equals(right));
    }

    public static MoValue notEqual(MoValue left, MoValue right) {
        return boolVal(!left.equals(right));
    }

    public static MoValue greater(MoValue left, MoValue right) {
        return boolVal(left.asDouble() > right.asDouble());
    }

    public static MoValue greaterOrEqual(MoValue left, MoValue right) {
        return boolVal(left.asDouble() >= right.asDouble());
    }

    public static MoValue smaller(MoValue left, MoValue right) {
        return boolVal(left.asDouble() < right.asDouble());
    }

    public static MoValue smallerOrEqual(MoValue left, MoValue right) {
        return boolVal(left.asDouble() <= right.asDouble());
    }

    public static MoValue negate(MoValue value) {
        return new DoubleValue(-value.asDouble());
    }

    // BooleanNotExpression: equals(ONE) ? ZERO : ONE
    public static MoValue not(MoValue value) {
        return value.equals(DoubleValue.ONE) ? DoubleValue.ZERO : DoubleValue.ONE;
    }

    // ---- truthiness ----

    // && and || use "not equal to zero". Uses the numeric value so a non-numeric operand (a string) is
    // the content-error 0.0 -> false, rather than coercing through equals.
    public static boolean notZero(MoValue value) {
        return value.asDouble() != 0.0;
    }

    // Ternary condition uses "equals one" (a quirk of the interpreter, preserved for parity).
    public static boolean isOne(MoValue value) {
        return value.asDouble() == 1.0;
    }

    public static MoValue boolVal(boolean b) {
        return b ? DoubleValue.ONE : DoubleValue.ZERO;
    }
}
