package org.cloudburstmc.mojava.runtime;

import org.cloudburstmc.mojava.runtime.value.MoValue;

public class MoScope {
    /**
     * Shared, never-mutated scope handed to scripts that declare {@code usesScope() == false}. Those
     * scripts emit no break/continue/return/loop code, so they never write it; concurrent reads of a
     * never-written object are safe. Saves a per-eval allocation on the common control-flow-free path.
     */
    public static final MoScope SHARED = new MoScope();

    private static final int BREAK = 1;
    private static final int CONTINUE = 2;
    private static final int RETURN = 4;

    // The three control signals collapsed into one word. A statement block re-checks "should I stop?"
    // after every child; with one int that poll is a single load + branch ({@link #isInterrupted})
    // instead of three getter calls. The getters/setters keep their original signatures so the
    // generated bytecode (and MoRuntime) are unchanged.
    private int flags = 0;
    private MoValue returnValue;

    public boolean isBreak() {
        return (flags & BREAK) != 0;
    }

    public void setBreak(boolean value) {
        if (value) {
            flags |= BREAK;
        } else {
            flags &= ~BREAK;
        }
    }

    public boolean isContinue() {
        return (flags & CONTINUE) != 0;
    }

    public void setContinue(boolean value) {
        if (value) {
            flags |= CONTINUE;
        } else {
            flags &= ~CONTINUE;
        }
    }

    public MoValue getReturnValue() {
        return returnValue;
    }

    public void setReturnValue(MoValue value) {
        this.returnValue = value;
        // Keep the RETURN bit in lockstep with returnValue so isInterrupted() is a single field read.
        if (value != null) {
            flags |= RETURN;
        } else {
            flags &= ~RETURN;
        }
    }

    /** True if any of return/break/continue is set — the single-load interrupt check used by codegen. */
    public boolean isInterrupted() {
        return flags != 0;
    }
}
